### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by iotaka** [jirutka/change-password#1]
Hello I had to install also this package: configparser

Cheers,

Iotaka

**Comment by jirutka** [comment]
Do you have Python 3.x? It already contains `configparser`.

**Comment by iotaka** [comment]
On ubuntu 16.04 was missing
Il 10 giu 2016 18:53, "Jakub Jirutka" <notifications@github.com> ha scritto:

**Comment by jirutka** [comment]
And have you installed Python 3? Ubuntu provides Python 2 as default.

**Comment by iotaka** [comment]
Python --version give: 2.7.11+
Il 10 giu 2016 18:55, "Jakub Jirutka" <notifications@github.com> ha scritto:

**Comment by jirutka** [comment]
Well, then I’m glad that it works even on Legacy Python; I’ve tested it only on Python 3.x. It’s also stated in [requirements](https://github.com/jirutka/change-password#requirements).

So you’ve just installed `configparser` and it fully works on Python 2.7.11?

**Comment by iotaka** [comment]
Hello, with configparser work with Python 2.7.11. You have a problem on the function at line 90

https://github.com/jirutka/change-password/blob/master/app.py#L90

you switched the parameters old password / new password http://ldap3.readthedocs.io/ldap3.extend.microsoft.modifyPassword.html#module-ldap3.extend.microsoft.modifyPassword

at line you did right https://github.com/jirutka/change-password/blob/master/app.py#L81

**Comment by jirutka** [comment]
I’ve added conditional requirement on configparser in 4aae9c9202bac4b12b52fcd25582247cc253cde6.
