### ISSUE TITLE
ImportError: cannot import name 'LDAPBindError'

### ISSUE THREAD

**Issue by tuchinsky** [jirutka/change-password#3]
Hello

I create virtualenv, install inside requirements packages via pip, and when run python3 app.py, I see error:

(test) [root@ansible-dev change-password]# which python3
/root/test/bin/python3
(test) [root@ansible-dev change-password]# python3 app.py
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from ldap3 import Connection, LDAPBindError, LDAPInvalidCredentialsResult, Server
ImportError: cannot import name 'LDAPBindError'
(test) [root@ansible-dev change-password]#

**Comment by jirutka** [comment]
Hi, what version of Python 3 and ldap3 do you have?

**Comment by tuchinsky** [comment]
(test) [root@ansible-dev test]# pip list|grep ldap3
ldap3 (2.2.2)
(test) [root@ansible-dev test]# python3 --version
Python 3.4.5
(test) [root@ansible-dev test]# python --version
Python 3.4.5

**Comment by jcnengel** [comment]
Just a few changes in ldap3 which require revised bindings...
[fix_ldap_bindings.patch.txt](https://github.com/jirutka/change-password/files/958285/fix_ldap_bindings.patch.txt)

**Comment by tuchinsky** [comment]
thanks, this patch fixed startup error
