### ISSUE TITLE
ldap3: cannot import name 'SUBTREE'

### ISSUE THREAD

**Issue by freeman-endlessm** [jirutka/change-password#4]
Hello, I'm trying to test out your app here. Using the python3, ldap3, and bottle modules that ship with Ubuntu 14.04. the ldap3 version meets your documented requirement, but the app fails to run.

```
sysmgr@ubuntu-14-04-5:~/change-password$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from ldap3 import AUTH_SIMPLE, SUBTREE
ImportError: cannot import name 'SUBTREE'
```

Python Versions:
```
ii  python3                            3.4.0-0ubuntu2                    amd64        interactive high-level object-oriented language (default python3 version)
ii  python3-bottle                     0.12.0-1                          all          fast and simple WSGI-framework for Python3
ii  python3-ldap3                      0.9.4.2-1~ubuntu14.04.1           all          Pure Python LDAP client library
```

**Comment by jirutka** [comment]
It seems that ldap3 developers don’t understand semantic versioning. :( So I don’t know what is minimal required version, probably ≥0.9.7 should be okay. 0.9.4.2 is ancient, it’s not even tagged in ldap3 repository.
